use tauri_specta::{collect_commands, Builder};
use crate::commands::{
    accounts, miniflux, notifications, preferences, quick_pane, recovery, tray,
};

fn main() {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            preferences::greet,
            preferences::load_preferences,
            preferences::save_preferences,
            notifications::send_native_notification,
            recovery::save_emergency_data,
            recovery::load_emergency_data,
            recovery::cleanup_old_recovery_files,
            quick_pane::show_quick_pane,
            quick_pane::dismiss_quick_pane,
            quick_pane::toggle_quick_pane,
            quick_pane::get_default_quick_pane_shortcut,
            quick_pane::update_quick_pane_shortcut,
            tray::tray_show_window,
            tray::tray_hide_window,
            tray::tray_toggle_window,
            tray::tray_set_icon_state,
            tray::tray_set_tooltip,
            tray::tray_get_state,
            tray::tray_is_window_visible,
            accounts::save_miniflux_account,
            accounts::get_miniflux_accounts,
            accounts::get_active_miniflux_account,
            accounts::delete_miniflux_account,
            accounts::auto_reconnect_miniflux,
            miniflux::miniflux_connect,
            miniflux::miniflux_disconnect,
            miniflux::miniflux_is_connected,
            miniflux::get_categories,
            miniflux::get_feeds,
            miniflux::get_category_feeds,
            miniflux::get_entries,
            miniflux::get_entries_list,
            miniflux::get_entry,
            miniflux::mark_entry_read,
            miniflux::mark_entries_read,
            miniflux::toggle_entry_star,
            miniflux::update_entry,
            miniflux::refresh_feed,
            miniflux::refresh_all_feeds,
            miniflux::create_feed,
            miniflux::update_feed,
            miniflux::delete_feed,
            miniflux::get_current_user,
            miniflux::get_counters,
            miniflux::discover_subscriptions,
            miniflux::export_opml,
            miniflux::import_opml,
            miniflux::fetch_entry_content,
        ])
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::String)
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
    println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
}
