/**
 * Emits the `_redirects` file the PWA needs on Netlify.
 *
 * Usage:
 *   MINIFLUX_URL=https://reader.example.com bun run scripts/write-deploy-redirects.ts
 *
 * Why this exists: Miniflux sends no CORS headers, so the browser build never
 * calls it cross-origin. Every request goes to the same-origin `/miniflux-api`
 * prefix and the *deployment* decides what that resolves to (see
 * `docs/developer/pwa.md`). Netlify can do that rewrite declaratively — but
 * `netlify.toml` cannot interpolate environment variables, so the rule has to
 * be generated at build time from `MINIFLUX_URL`.
 *
 * Two rules are written, and the order matters — Netlify applies the first
 * match, so the API proxy must come before the SPA catch-all:
 *
 *   /miniflux-api/*  https://reader.example.com/:splat  200!   (proxy)
 *   /*               /index.html                        200    (SPA fallback)
 *
 * The `!` forces the proxy to win even when a file of that name exists.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT_DIR = process.env.DEPLOY_OUT_DIR ?? 'dist';
const rawUrl = process.env.MINIFLUX_URL?.trim();

if (!rawUrl) {
  console.error(
    'MINIFLUX_URL is not set.\n\n' +
      'The PWA proxies /miniflux-api to your Miniflux instance, so the deploy\n' +
      "needs to know its address. Set it in your host's environment settings:\n\n" +
      '  MINIFLUX_URL=https://reader.example.com\n'
  );
  process.exit(1);
}

// A dashboard-entered value is often a bare hostname; `new URL()` rejects that,
// so assume https the way `vite.config.ts` and `deploy/miniflux-proxy.ts` do.
const withScheme = /^https?:\/\//i.test(rawUrl)
  ? rawUrl
  : `${/^(localhost|127\.0\.0\.1|\[::1\])(:|$)/i.test(rawUrl) ? 'http' : 'https'}://${rawUrl}`;

let target: URL;
try {
  target = new URL(withScheme);
} catch {
  console.error(`MINIFLUX_URL is not a valid URL: ${rawUrl}`);
  process.exit(1);
}

if (target.protocol !== 'https:' && target.hostname !== 'localhost') {
  console.error(
    `MINIFLUX_URL must use https (got ${target.protocol}//). ` +
      'Credentials cross this hop, so plaintext is not acceptable off localhost.'
  );
  process.exit(1);
}

// Trailing slashes would produce `//v1/...` once `:splat` is appended.
const base = `${target.origin}${target.pathname.replace(/\/+$/, '')}`;

const contents = `# Generated by scripts/write-deploy-redirects.ts — do not edit by hand.
# Order matters: the API proxy must be matched before the SPA fallback.

/miniflux-api/*  ${base}/:splat  200!
/*               /index.html     200
`;

const outPath = join(OUT_DIR, '_redirects');
writeFileSync(outPath, contents);
console.log(`Wrote ${outPath} — /miniflux-api/* proxies to ${base}`);
