use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        accounts, counters, data, downloads, miniflux, notifications, preferences, quick_pane,
        reading_state, recovery, sync, tray,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        downloads::download_file,
        downloads::cancel_download,
        downloads::retry_download,
        downloads::get_downloads,
        downloads::get_downloads_from_db,
        data::clear_local_data,
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        reading_state::load_last_reading,
        reading_state::save_last_reading,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        tray::tray_show_window,
        tray::tray_hide_window,
        tray::tray_set_icon_state,
        tray::tray_set_tooltip,
        tray::tray_get_state,
        tray::tray_is_window_visible,
        accounts::save_miniflux_account,
        accounts::get_miniflux_accounts,
        accounts::get_active_miniflux_account,
        accounts::switch_miniflux_account,
        accounts::delete_miniflux_account,
        accounts::auto_reconnect_miniflux,
        miniflux::miniflux_connect,
        miniflux::miniflux_disconnect,
        miniflux::miniflux_is_connected,
        miniflux::get_categories,
        miniflux::get_feeds,
        miniflux::get_category_feeds,
        miniflux::get_entries,
        miniflux::get_entry,
        miniflux::mark_entry_read,
        miniflux::mark_entries_read,
        miniflux::toggle_entry_star,
        miniflux::update_entry,
        miniflux::refresh_feed,
        miniflux::refresh_all_feeds,
        miniflux::create_feed,
        miniflux::update_feed,
        miniflux::delete_feed,
        miniflux::get_current_user,
        miniflux::get_counters,
        miniflux::discover_subscriptions,
        miniflux::export_opml,
        miniflux::import_opml,
        miniflux::fetch_entry_content,
        sync::sync_miniflux,
        counters::get_unread_counts,
    ])
}

/// Export TypeScript bindings to frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::String)
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
